import React from "react";
import "bootstrap/dist/css/bootstrap.css";
import "../css/lineicons.css";

import "../css/tiny-slider.min.css";
import "../css/main.css";

import { getMainMenu } from "../lib/api";
import FooterSection from "../components/footer-section";
import HeaderSection from "../components/header-section";
import ScrollToButtonButton from "../components/scroll-to-top-button";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const test = await getMainMenu();

	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap"
					rel="stylesheet"
				/>
			</head>

			<body>
				<HeaderSection mainMenu={test} />

				{children}
				<FooterSection mainMenu={test} />
				<ScrollToButtonButton />
			</body>
		</html>
	);
}
